const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]═══════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT 
global.appUrl=process.env.APP_URL || ""     // put your deploy app/bot url here, for 24/7 for (render , koyeb, glitch)
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || "false"  
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || "false"

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "";
global.gurl  =process.env.GURL  || "";
global.website =process.env.GURL || "" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "" || "" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "Made With LOVE!" 


global.devs = "" // Developer Contacts
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "255767886564";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '1'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || Math.floor(Math.random()*3)  === 1 ?  "" : "false" ;  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "" //"https://i.ibb.co/pXyNHj8/suhail.jpg" // "image" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "recording" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com/" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";

global.SESSION_ID = process.env.SESSION_ID  || "SUHAIL_11_51_09_10_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTI4LFxuICAgICAgICAyNDgsXG4gICAgICAgIDE2MyxcbiAgICAgICAgMTk5LFxuICAgICAgICAyMzIsXG4gICAgICAgIDIwMCxcbiAgICAgICAgNjEsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTY4LFxuICAgICAgICAyMjMsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMTMxLFxuICAgICAgICAyMzQsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTY4LFxuICAgICAgICA1MyxcbiAgICAgICAgMTM0LFxuICAgICAgICAxOTYsXG4gICAgICAgIDcxLFxuICAgICAgICAyNDUsXG4gICAgICAgIDg1LFxuICAgICAgICAxODcsXG4gICAgICAgIDIxOCxcbiAgICAgICAgNTUsXG4gICAgICAgIDc4LFxuICAgICAgICAyNDIsXG4gICAgICAgIDkxLFxuICAgICAgICA2NixcbiAgICAgICAgMTg0LFxuICAgICAgICAxOTgsXG4gICAgICAgIDE0NCxcbiAgICAgICAgODJcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTU1LFxuICAgICAgICA5MixcbiAgICAgICAgMTY0LFxuICAgICAgICAxMjksXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjI5LFxuICAgICAgICAxMzEsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTE5LFxuICAgICAgICAyMDQsXG4gICAgICAgIDQxLFxuICAgICAgICAyMjgsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTQ5LFxuICAgICAgICAyMzYsXG4gICAgICAgIDExMyxcbiAgICAgICAgOTcsXG4gICAgICAgIDIzMSxcbiAgICAgICAgNzEsXG4gICAgICAgIDIwNixcbiAgICAgICAgNDksXG4gICAgICAgIDQyLFxuICAgICAgICAyNixcbiAgICAgICAgMjI0LFxuICAgICAgICAxOTUsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTAxLFxuICAgICAgICAyNTIsXG4gICAgICAgIDM4LFxuICAgICAgICA0NCxcbiAgICAgICAgMTk1LFxuICAgICAgICA3OVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTQ0LFxuICAgICAgICAxNTYsXG4gICAgICAgIDExOCxcbiAgICAgICAgNDAsXG4gICAgICAgIDg2LFxuICAgICAgICAxOTMsXG4gICAgICAgIDQxLFxuICAgICAgICAyMTIsXG4gICAgICAgIDE0LFxuICAgICAgICAxMzgsXG4gICAgICAgIDE0NixcbiAgICAgICAgMjMsXG4gICAgICAgIDMsXG4gICAgICAgIDE4MixcbiAgICAgICAgNzEsXG4gICAgICAgIDc0LFxuICAgICAgICAxMDksXG4gICAgICAgIDI0MCxcbiAgICAgICAgNTUsXG4gICAgICAgIDY0LFxuICAgICAgICA1NCxcbiAgICAgICAgMTcyLFxuICAgICAgICAxMTEsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMjEzLFxuICAgICAgICAxNDUsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTczLFxuICAgICAgICAyMjMsXG4gICAgICAgIDgyLFxuICAgICAgICAyMzEsXG4gICAgICAgIDExNlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMzcsXG4gICAgICAgIDcsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMjU0LFxuICAgICAgICAxMTgsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTQwLFxuICAgICAgICAxMTMsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMTAzLFxuICAgICAgICA2LFxuICAgICAgICAxMTMsXG4gICAgICAgIDEyNixcbiAgICAgICAgMjQ5LFxuICAgICAgICAyNTUsXG4gICAgICAgIDU0LFxuICAgICAgICAyMjMsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTM3LFxuICAgICAgICAyNDUsXG4gICAgICAgIDg2LFxuICAgICAgICAyMTIsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMTYwLFxuICAgICAgICA3NSxcbiAgICAgICAgMTY3LFxuICAgICAgICAzNCxcbiAgICAgICAgMTkyLFxuICAgICAgICAzMSxcbiAgICAgICAgNDksXG4gICAgICAgIDMyLFxuICAgICAgICAxMDFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIxNixcbiAgICAgICAgMTE5LFxuICAgICAgICAyMTEsXG4gICAgICAgIDc1LFxuICAgICAgICAxMDgsXG4gICAgICAgIDk3LFxuICAgICAgICA5OSxcbiAgICAgICAgMyxcbiAgICAgICAgMTY1LFxuICAgICAgICAxOTIsXG4gICAgICAgIDI0NSxcbiAgICAgICAgOTQsXG4gICAgICAgIDAsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTY2LFxuICAgICAgICAyMjQsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTI1LFxuICAgICAgICAyLFxuICAgICAgICA0NSxcbiAgICAgICAgMTE4LFxuICAgICAgICAyMTksXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTMyLFxuICAgICAgICAyMzEsXG4gICAgICAgIDc1LFxuICAgICAgICAyMDQsXG4gICAgICAgIDIxMCxcbiAgICAgICAgNDAsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTU4LFxuICAgICAgICAxMTRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjM3LFxuICAgICAgICAxNTYsXG4gICAgICAgIDE3LFxuICAgICAgICAxNixcbiAgICAgICAgMjIzLFxuICAgICAgICA4MixcbiAgICAgICAgMTUyLFxuICAgICAgICAxNjYsXG4gICAgICAgIDE0NyxcbiAgICAgICAgODIsXG4gICAgICAgIDc3LFxuICAgICAgICAxNTEsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMjgsXG4gICAgICAgIDIyMyxcbiAgICAgICAgODMsXG4gICAgICAgIDE1NSxcbiAgICAgICAgOTgsXG4gICAgICAgIDI2LFxuICAgICAgICAyMjYsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMjMwLFxuICAgICAgICAxMzksXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTg0LFxuICAgICAgICAxNTUsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTU0LFxuICAgICAgICA2NCxcbiAgICAgICAgNixcbiAgICAgICAgMTcsXG4gICAgICAgIDExMlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgMTk0LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDcsXG4gICAgICAgICAgMixcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgMTIxLFxuICAgICAgICAgIDYyLFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgNyxcbiAgICAgICAgICAxOTMsXG4gICAgICAgICAgMjEyLFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgMTI0LFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICA5NyxcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgMixcbiAgICAgICAgICAxOTcsXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDMyLFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICAyNTMsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMjM2LFxuICAgICAgICAgIDExM1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMjEsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgNjcsXG4gICAgICAgICAgMzYsXG4gICAgICAgICAgMixcbiAgICAgICAgICA5OCxcbiAgICAgICAgICA0MixcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDIyMixcbiAgICAgICAgICAxLFxuICAgICAgICAgIDU1LFxuICAgICAgICAgIDYyLFxuICAgICAgICAgIDEyMyxcbiAgICAgICAgICAyNyxcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICA4NCxcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgMTI3LFxuICAgICAgICAgIDYsXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDE3NyxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDE1MSxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMTE1XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTU5LFxuICAgICAgICAxMDksXG4gICAgICAgIDE2NSxcbiAgICAgICAgMTY2LFxuICAgICAgICA5MyxcbiAgICAgICAgMjIsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTAxLFxuICAgICAgICAxNTUsXG4gICAgICAgIDE0MyxcbiAgICAgICAgNDUsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTM4LFxuICAgICAgICAxMjksXG4gICAgICAgIDIwMixcbiAgICAgICAgMTI2LFxuICAgICAgICAxMzEsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMjQwLFxuICAgICAgICAxMTAsXG4gICAgICAgIDkwLFxuICAgICAgICA3NyxcbiAgICAgICAgMTAwLFxuICAgICAgICAxNDUsXG4gICAgICAgIDE3OSxcbiAgICAgICAgOTIsXG4gICAgICAgIDYwLFxuICAgICAgICA1LFxuICAgICAgICA5MixcbiAgICAgICAgMjMsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTYwLFxuICAgICAgICAyMDMsXG4gICAgICAgIDEwLFxuICAgICAgICA3MyxcbiAgICAgICAgMTc1LFxuICAgICAgICAyMTksXG4gICAgICAgIDIxNSxcbiAgICAgICAgOTQsXG4gICAgICAgIDE4NSxcbiAgICAgICAgNjMsXG4gICAgICAgIDIwNixcbiAgICAgICAgMjM2LFxuICAgICAgICA3MSxcbiAgICAgICAgMjI2LFxuICAgICAgICA3MyxcbiAgICAgICAgODQsXG4gICAgICAgIDIsXG4gICAgICAgIDM5LFxuICAgICAgICAxNTksXG4gICAgICAgIDAsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTM3LFxuICAgICAgICA2MSxcbiAgICAgICAgNTMsXG4gICAgICAgIDExMixcbiAgICAgICAgMTM4LFxuICAgICAgICAxMTAsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTc0LFxuICAgICAgICAxNjAsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTY1LFxuICAgICAgICAxMzRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDEzMyxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJNM3Q2ZHphbmdCbEtSUC8wM0kyaElmRWZUeDUvRzQxNFYzajNWa1dzbFRzPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJqdmNGbHBVN1RLLU0tWTVHNW5kVTZRXCIsXG4gIFwicGhvbmVJZFwiOiBcIjk2OTkwZTA5LTEwMjEtNDRhZC1hNjEzLTU1MDVmNThlYzkwNlwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxOTEsXG4gICAgICAxMDYsXG4gICAgICA3NyxcbiAgICAgIDE1NCxcbiAgICAgIDEzOCxcbiAgICAgIDE0NSxcbiAgICAgIDY0LFxuICAgICAgMjEyLFxuICAgICAgNDgsXG4gICAgICAyNDQsXG4gICAgICAyMjIsXG4gICAgICA5NixcbiAgICAgIDEyNyxcbiAgICAgIDIzOCxcbiAgICAgIDE3NixcbiAgICAgIDE2MyxcbiAgICAgIDEyNCxcbiAgICAgIDg1LFxuICAgICAgMzYsXG4gICAgICAxMDhcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiBmYWxzZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDksXG4gICAgICAxNTMsXG4gICAgICA4MyxcbiAgICAgIDIyMSxcbiAgICAgIDEzLFxuICAgICAgMTUwLFxuICAgICAgMTU2LFxuICAgICAgMjMxLFxuICAgICAgMjE0LFxuICAgICAgMzgsXG4gICAgICA1NixcbiAgICAgIDMsXG4gICAgICAyMjQsXG4gICAgICAyMTAsXG4gICAgICAxMTEsXG4gICAgICAxNTUsXG4gICAgICAyMjUsXG4gICAgICA2NCxcbiAgICAgIDEwNCxcbiAgICAgIDEzXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDSmVEK2I0SUVKN01oY1lHR0FVZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCIwekZNSkU0WFdTdG5ieFljSG9aS2hMeW82c1F5SFErbVFCZDFmVzFOM0M4PVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcInNIcUJHRWlxbXFLMCtxTlZSNUozeU14d2Jwbno4SUdXUXhpNUNzNUtQNHVuSW5oTkE3Z1JIdFdRUk1VZTBNMFA0MmRzR3hIV1R5Vmd3RmhEcms3QkN3PT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcInFJNERuVGxMdUFMTEgvT3VaZnNVakxKcFJsZnV4VVc3Vks3RWNJOWc2T2hpVGd6V0xtak5HVGo5RTlET3JFRDVQOXNGN3FaNzJqNjAvTTYxRjNuVmdRPT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjU1NzY3ODg2NTY0OjE0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCI1NjEzOTcwMjA5NTk2NjoxNEBsaWRcIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjI1NTc2Nzg4NjU2NDoxNEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICA0OSxcbiAgICAgICAgICA3NixcbiAgICAgICAgICAzNixcbiAgICAgICAgICA3OCxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgMTExLFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDMwLFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAxMzIsXG4gICAgICAgICAgMTg4LFxuICAgICAgICAgIDE2OCxcbiAgICAgICAgICAyMzQsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDUwLFxuICAgICAgICAgIDI5LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICA2NCxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAxMTcsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDEwOSxcbiAgICAgICAgICA3NyxcbiAgICAgICAgICAyMjAsXG4gICAgICAgICAgNDdcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImlwaG9uZVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzU3NTA1MDU4LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBS0psXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLSlouanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJNTXdaMnF3YUt1WWRkSFJ2bC9LZVJOVURNME9WVXJZejdwOXM2SFJUbW9zPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjIyNzk0ODk5NDMsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlsxLDBdfSxcInRpbWVzdGFtcFwiOlwiMTc0MTk5MzQxNTQ2NVwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUtKYS5qc29uIjogIntcImtleURhdGFcIjpcIjRqWUxrNjJoR1FHVWZIZmFZY3dLWnNHSTkyV2NYNlhjU2I1ZUpxZGNFa2c9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjI3OTQ4OTk0MyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzEsMF19LFwidGltZXN0YW1wXCI6XCIxNzQ0NjA1OTYyMTQ4XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBS0piLmpzb24iOiAie1wia2V5RGF0YVwiOlwiMTQrQkM3cSthVlhvVENZdDQzSVZGZ1RESG53VTdXYkxnTTk2QUdsVDgvZz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyMjc5NDg5OTQzLFwiY3VycmVudEluZGV4XCI6MixcImRldmljZUluZGV4ZXNcIjpbMiwxLDBdfSxcInRpbWVzdGFtcFwiOlwiMTc0NzE5OTIzNTkyOFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUtKYy5qc29uIjogIntcImtleURhdGFcIjpcImJmWTc2TEV4QTZNYjBaaERKendmYy9paGRrdDBDOVFSTUNwV0ZJUGJ0ems9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjI3OTQ4OTk0MyxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzIsMSwwXX0sXCJ0aW1lc3RhbXBcIjpcIjE3NDk3OTE0MTgxOTlcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLSmUuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCI0b3lLN1pIUVFrajVXMzVpL0JoS0Q1V0F5TFI5ZkJNdHlnbUFzVTRGWVlFPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjIyNzk0ODk5NDMsXCJjdXJyZW50SW5kZXhcIjoyLFwiZGV2aWNlSW5kZXhlc1wiOlsyLDAsMV19LFwidGltZXN0YW1wXCI6XCIxNzUwNDM4MDMzMzc1XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBS0pmLmpzb24iOiAie1wia2V5RGF0YVwiOlwicms3U3R2aDBaVU9MYXllNzRnSE5KNzI1ZGhkM0F4NW9uU2xaTVREZHJidz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyMjc5NDg5OTQzLFwiY3VycmVudEluZGV4XCI6MyxcImRldmljZUluZGV4ZXNcIjpbMCwzLDFdfSxcInRpbWVzdGFtcFwiOlwiMTc1MDQ0OTkwMDEzN1wifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUtKaC5qc29uIjogIntcImtleURhdGFcIjpcIkFwS1BpMFJaeW9uZnF2SmZ6Q3FIVldrbTJCQ0FoNVBTSUdiMHRENFE4Zjg9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjI3OTQ4OTk0MyxcImN1cnJlbnRJbmRleFwiOjMsXCJkZXZpY2VJbmRleGVzXCI6WzEsMywwXX0sXCJ0aW1lc3RhbXBcIjpcIjE3NTA1Nzk2OTY5NjNcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLSmkuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJuRjh0Smd3bWo5TFNzWTBHd3d4UHVTbVFiRXBZc3BqeFVDT3FHUDFhbEE4PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjIyNzk0ODk5NDMsXCJjdXJyZW50SW5kZXhcIjozLFwiZGV2aWNlSW5kZXhlc1wiOlsxLDBdfSxcInRpbWVzdGFtcFwiOlwiMTc1MDU3OTY5ODExNVwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUtKai5qc29uIjogIntcImtleURhdGFcIjpcIlpqSXZBWmZVMDYrTVFNNVlGV1ZjM2ZTVjVRUFFiTG1iMHdxY2lPVEVWajg9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjI3OTQ4OTk0MyxcImN1cnJlbnRJbmRleFwiOjQsXCJkZXZpY2VJbmRleGVzXCI6WzEsMCw0XX0sXCJ0aW1lc3RhbXBcIjpcIjE3NTMxNzU1NDgwMDdcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLSmsuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJYZTJLK3lndkREQnJCLzBzeDkvL0dMN2RMNU5nV0xTWXJqWGoyN0JYNnpFPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjIyNzk0ODk5NDMsXCJjdXJyZW50SW5kZXhcIjo0LFwiZGV2aWNlSW5kZXhlc1wiOls0LDEsMF19LFwidGltZXN0YW1wXCI6XCIxNzU1NzY5MjkzNjc4XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBS0psLmpzb24iOiAie1wia2V5RGF0YVwiOlwieWRQN1RsQ25jUm1VNkl0Mjg5M3VoUEg3bFpxRWprRHR3eDd2Nno0cWVwUT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyMjc5NDg5OTQzLFwiY3VycmVudEluZGV4XCI6NCxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3NTY1OTE4MTkwNDlcIn0iCn0="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "3.0.1-developement",
  caption : global.caption || "vench" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ GlobalTechInfo ® 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@GlobalTechInfo"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "vench",
  ownername:process.env.OWNER_NAME|| "vench",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "public",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",

